version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-v1-

      - run:
          name: Build and run tests against qa
          command: ./gradlew clean build smokeTest regressionTest -Denv=qa --no-daemon

      - save_cache:
          key: gradle-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/reports

workflows:
  test-on-push:
    jobs:
      - build-and-test
